#! /bin/bash
echo "##############################################"
echo "#                                            #"
echo "#   Install script for JIRA - START          #"
echo "#                                            #"
echo "##############################################"
echo ""
echo "### Step 1 - Download JIRA install archive"
cd /tmp/
wget --no-check-certificate --progress=bar --show-progress https://downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-7.5.0.tar.gz
echo "### DONE"
echo ""
echo "### Step 2 - creating dedicated user 'jira'"
sudo useradd --create-home -c "JIRA role account" {{REMOTE_SERVER_USER}}
echo "### DONE"
echo ""
echo "### Step 3 - creating folders for installing JIRA and JIRA Home"
sudo mkdir /var/atlassian && sudo mkdir /var/atlassian/application-data && sudo mkdir /var/atlassian/application-data/jira && sudo mkdir /var/atlassian/application-data/jira/data
sudo mkdir /opt/atlassian && sudo mkdir /opt/atlassian/jira
echo "### DONE"
echo ""
echo "### Step 4 - changing permissions for jira folders"
sudo chown -R {{REMOTE_SERVER_USER}}:{{REMOTE_SERVER_USER}} /opt/atlassian/jira
sudo chown -R {{REMOTE_SERVER_USER}}:{{REMOTE_SERVER_USER}} /var/atlassian/application-data/jira
sudo chown -R {{REMOTE_SERVER_USER}}:{{REMOTE_SERVER_USER}} /jira-files
cd /opt/atlassian/jira
echo "### DONE"
echo ""
echo "### Step 5 - unpack JIRA and add symlink"
sudo su {{REMOTE_SERVER_USER}} -c 'tar -zxf /tmp/atlassian-jira-software-7.5.0.tar.gz'
sudo su {{REMOTE_SERVER_USER}} -c 'ln -s atlassian-jira-software-7.5.0-standalone/ current'
echo "### DONE"
echo ""
echo "### Step 6 - add JIRA home directory to properties"
echo "jira.home=/var/atlassian/application-data/jira" > /opt/atlassian/jira/current/atlassian-jira/WEB-INF/classes/jira-application.properties
echo "### DONE"
echo ""
echo "### Step 7 - copy config files into install folder"
cp /tmp/server.xml /opt/atlassian/jira/current/conf/
cp /tmp/dbconfig.xml /var/atlassian/application-data/jira/
echo "### DONE"
echo ""
echo "##############################################"
echo "#                                            #"
echo "#   Install script for JIRA - DONE           #"
echo "#                                            #"
echo "##############################################"
echo ""
echo ""
echo ""
echo "##############################################"
echo "#                                            #"
echo "#  Configuring SSH Access - START            #"
echo "#                                            #"
echo "##############################################"
echo ""
echo "### Step 1 - Generating RSA-Key"
echo -e 'y\n'|ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa 1> /dev/null
echo "### DONE"
echo ""
echo "### Step 2 - Adding remote host to known_hosts"
ssh-keyscan -t rsa,dsa {{REMOTE_SERVER_IP}} >> ~/.ssh/known_hosts
echo "### DONE"
echo ""
echo "### Step 3 - Copy RSA-Key to remote hosts"
sshpass -p {{REMOTE_SERVER_PASS}} ssh-copy-id {{REMOTE_SERVER_USER}}@{{REMOTE_SERVER_IP}}
echo "### DONE"
echo ""
echo "### Step 4 - Test Connection to remote host and create folder for file storage"
ssh {{REMOTE_SERVER_USER}}@{{REMOTE_SERVER_IP}} "mkdir ~/jira-files"
echo "### DONE"
echo ""
echo "##############################################"
echo "#                                            #"
echo "#  Configuring SSH Access - DONE             #"
echo "#                                            #"
echo "##############################################"
echo ""
echo ""
echo ""
echo "##############################################"
echo "#                                            #"
echo "#  Starting up services for JIRA - START     #"
echo "#                                            #"
echo "##############################################"
echo ""
echo "### Step 1 - Starting up JIRA"
sudo /etc/init.d/jira start
echo "### DONE"
echo ""
echo "### Step 2 - Starting up nginx"
sudo /etc/init.d/nginx start
echo "### DONE"
echo ""
echo "### Step 3 - Mount file folder"
rm -rf /var/atlassian/application-data/jira/data/attachments
rm -rf /var/atlassian/application-data/jira/data/avatars
sshfs -o allow_other -o reconnect -o nonempty -o ServerAliveInterval=15 -o IdentityFile=~/.ssh/id_rsa {{REMOTE_SERVER_USER}}@{{REMOTE_SERVER_IP}}:/home/{{REMOTE_SERVER_USER}}/jira-files /var/atlassian/application-data/jira/data/
echo "### DONE"
echo ""
echo "##############################################"
echo "#                                            #"
echo "#  Starting up services for JIRA - DONE      #"
echo "#                                            #"
echo "##############################################"
